In [1]:
import pandas as pd

df = pd.read_csv("./data/train.csv")
df.head()

id                    epoch  sat_id             x             y  \
0   0  2014-01-01T00:00:00.000       0  -8855.823863  13117.780146   
1   1  2014-01-01T00:46:43.000       0 -10567.672384   1619.746066   
2   2  2014-01-01T01:33:26.001       0 -10578.684043 -10180.467460   
3   3  2014-01-01T02:20:09.001       0  -9148.251857 -20651.437460   
4   4  2014-01-01T03:06:52.002       0  -6719.092336 -28929.061629   

              z        Vx        Vy        Vz         x_sim         y_sim  \
0 -20728.353233 -0.908303 -3.808436 -2.022083  -8843.131454  13138.221690   
1 -24451.813271 -0.302590 -4.272617 -0.612796 -10555.500066   1649.289367   
2 -24238.280949  0.277435 -4.047522  0.723155 -10571.858472 -10145.939908   
3 -20720.381279  0.715600 -3.373762  1.722115  -9149.620794 -20618.200201   
4 -14938.907967  0.992507 -2.519732  2.344703  -6729.358857 -28902.271436   

          z_sim    Vx_sim    Vy_sim    Vz_sim  
0 -20741.615306 -0.907527 -3.804930 -2.024133  
1 -24473.089556 -0.303704 -4.269816 -0.616468  
2 -24271.169776  0.274880 -4.046788  0.718768  
3 -20765.019094  0.712437 -3.375202  1.718306  
4 -14992.399986  0.989382 -2.522618  2.342237

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
sim = scaler.fit_transform(df[["x_sim", "y_sim"]])

# x = np.array(df.z)
# np.mean(x), np.std(x)

In [41]:
sim

array([[-0.31108233,  0.5003881 ],
       [-0.37856735,  0.05173229],
       [-0.37921204, -0.40888476],
       ...,
       [-0.88721012, -0.23019566],
       [-0.86343975,  0.00190147],
       [-0.77664436,  0.23248613]])

In [42]:
rev_sim = scaler.inverse_transform(sim)
rev_sim

array([[ -8843.1314537 ,  13138.22168963],
       [-10555.50006619,   1649.28936685],
       [-10571.85847173, -10145.93990816],
       ...,
       [-23461.83069857,  -5570.16717461],
       [-22858.67992929,    373.24910188],
       [-20656.3286029 ,   6277.93468298]])

In [43]:
df[["x_sim", "y_sim"]]

x_sim         y_sim
0       -8843.131454  13138.221690
1      -10555.500066   1649.289367
2      -10571.858472 -10145.939908
3       -9149.620794 -20618.200201
4       -6729.358857 -28902.271436
...              ...           ...
649907 -20717.958996 -16245.240500
649908 -22673.444496 -11192.339393
649909 -23461.830699  -5570.167175
649910 -22858.679929    373.249102
649911 -20656.328603   6277.934683

[649912 rows x 2 columns]

In [38]:
scaler.mean_ , scaler.scale_

(array([-949.71065994,  324.55719776]),
 array([25374.05674322, 25607.45266996]))

In [39]:
df.describe().iloc[2]

id        356657.040984
sat_id       171.482926
x          25391.507810
y          25631.511540
z          20652.050496
Vx             2.639041
Vy             2.597130
Vz             2.116245
x_sim      25374.076264
y_sim      25607.472371
z_sim      20667.988715
Vx_sim         2.637491
Vy_sim         2.600323
Vz_sim         2.113769
Name: std, dtype: float64

In [5]:
x = df.x
y = df.y
z = df.z
Vx = df.Vx
Vy = df.Vy
Vz = df.Vz

In [6]:
xdata = df[["x_sim", "y_sim", "z_sim" , "Vx_sim" , "Vy_sim", "Vz_sim"]]
ydata = x

In [7]:
X_train, X_test, y_train, y_test = train_test_split(xdata, ydata, test_size=0.33, random_state=42)

In [ ]:
from sklearn import svm

reg = svm.SVR()

reg.fit(X_train, y_train)

/home/gopi/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
